services:
  pgdatabase:
    image: postgres:15.4
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumnes:
      - "./pg_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"