openapi: 3.0.0
info:
  title: "Patel Recipe App"
  description: "An API about recipes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  parameters:
    recipe_id:
      name: "recipe_id"
      description: "ID of the recipe"
      in: path
      required: true
      schema:
        type: "integer"
    ingredient_id:
      name: "ingredient_id"
      description: "ID of the ingredient"
      in: path
      required: true
      schema:
        type: "integer"

paths:
  /recipe:
    get:
      operationId: "recipe.read_all"
      tags:
        - "Recipe"
      summary: "Read the list of recipes"
      responses:
        "200":
          description: "Successfully read recipe list"
  /recipe/{recipe_id}:
    get:
      operationId: "recipe.read_one"
      tags:
        - "Recipe"
      summary: "Read one recipe"
      parameters:
        - $ref: "#/components/parameters/recipe_id"
      responses:
        "200":
          description: "Successfully read recipe"
  /ingredients/{recipe_id}:
    get:
      operationId: "ingredient.read_all"
      tags:
        - "Ingredient"
      summary: "Read the ingredients for a recipe"
      parameters:
        - $ref: "#/components/parameters/recipe_id"
      responses:
        "200":
          description: "Successfully read ingredient list"
  /ingredient/{ingredient_id}:
    get:
      operationId: "ingredient.read_one"
      tags:
        - "Ingredient"
      summary: "Read one ingredient"
      parameters:
        - $ref: "#/components/parameters/ingredient_id"
      responses:
        "200":
          description: "Successfully read ingredient"