openapi: 3.0.0
info:
  title: "Patel Recipe App"
  description: "An API about recipes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Recipe:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
        date_created:
          type: "string"
        date_modified:
          type: "string"
        created_by:
          type: "integer"
        modified_by:
          type: "integer"
  parameters:
    recipe_id:
      name: "recipe_id"
      description: "ID of the recipe"
      in: path
      required: true
      schema:
        type: "integer"
    ingredient_id:
      name: "ingredient_id"
      description: "ID of the ingredient"
      in: path
      required: true
      schema:
        type: "integer"

paths:
  /recipe:
    get:
      operationId: "recipe.read_all"
      tags:
        - "Recipe"
      summary: "Read the list of recipes"
      responses:
        "200":
          description: "Successfully read recipe list"
    post:
      operationId: "recipe.create"
      tags:
        - Recipe
      summary: "Create a recipe"
      requestBody:
          description: "Recipe to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "recipe"
                $ref: "#/components/schemas/Recipe"
      responses:
        "201":
          description: "Successfully created recipe"
  /recipe/{recipe_id}:
    get:
      operationId: "recipe.read_one"
      tags:
        - "Recipe"
      summary: "Read one recipe"
      parameters:
        - $ref: "#/components/parameters/recipe_id"
      responses:
        "200":
          description: "Successfully read recipe"
  /ingredients/{recipe_id}:
    get:
      operationId: "ingredient.read_all"
      tags:
        - "Ingredient"
      summary: "Read the ingredients for a recipe"
      parameters:
        - $ref: "#/components/parameters/recipe_id"
      responses:
        "200":
          description: "Successfully read ingredient list"
  /ingredient/{ingredient_id}:
    get:
      operationId: "ingredient.read_one"
      tags:
        - "Ingredient"
      summary: "Read one ingredient"
      parameters:
        - $ref: "#/components/parameters/ingredient_id"
      responses:
        "200":
          description: "Successfully read ingredient"